### ISSUE TITLE
Sound Fix

### ISSUE THREAD

**Issue by chrisrock1984** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#10]
Hey and thank you for this great component. 
You mentioned, that you will add the audio fix, when it is available. 
As it is available, are there plans to implement it?
KR

**Comment by danielscheidler** [comment]
Yes, was a bit busy the last weeks. But I'm on the last steps for releasing the alternative yaml to use it for covers. Then I'll update the audio fix, too. 

But only add `i2s_comm_fmt: lsb` to the media_player component will do the trick

**Comment by Fabaderheld** [comment]
I love that! Now my switches can not only flash but make noise when someone rings my doorbell :D

**Comment by chrisrock1984** [comment]
Thank you so much for the info!!!
