### ISSUE TITLE
ble proxy

### ISSUE THREAD

**Issue by pablogpr** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#12]
I want to use my tx for the bluetooth proxy functionality, but:
Error: The program size (1941981 bytes) is greater than maximum allowed (1835008 bytes)

How can inprove the size of the overall firmware?, I have 1 gang switch, nothing connected to the relay, but i want to know with part of the touchpanel is used.
I already try to comment some features like logger, but without success.

**Comment by danielscheidler** [comment]
Yes, I've tried bt proxy too.
But unfortunately I had to leave it out for now. As soon as I see a way to free up enough space, I'll add the proxy back into the configuration as well.
What might work would be to omit the audio component. But I haven't tested it yet because I use the voice output of the TX.

**Comment by ChinHong-B** [comment]
how did you use the voice output of the TX? isnt it too noisy to be used?

**Comment by danielscheidler** [comment]
> how did you use the voice output of the TX? isnt it too noisy to be used? 

Add following to the Media component Like in my current config.

```
    i2s_comm_fmt: lsb
```

**Comment by brotaxt** [comment]
> Yes, I've tried bt proxy too. But unfortunately I had to leave it out for now. As soon as I see a way to free up enough space, I'll add the proxy back into the configuration as well. What might work would be to omit the audio component. But I haven't tested it yet because I use the voice output of the TX.

Just to confirm -> The ble proxy can be activated when omitting the audio component

**Comment by danielscheidler** [comment]
> Just to confirm -> The ble proxy can be activated when omitting the audio component

Thank you for confirm this

**Comment by robbiedehand** [comment]
@pablogpr how dit you get BLE proxy working, so what code did u use?

**Comment by yanirel** [comment]
@brotaxt can u please explain how have u deleted the audio component

**Comment by brotaxt** [comment]
@robbiedehand @yanirel  IIRC I removed the following part of my configuration. Thus the audio component does not get included and there is enough free space for the ble proxy.

https://github.com/SmartHome-yourself/sonoff-tx-ultimate-for-esphome/blob/7e745b3566df10d1de4fdb52c5b23442d28aa34a/tx_ultimate_cover.yaml#L526-L539

**Comment by danielscheidler** [comment]
I think with the answer of @brotaxt this issue can be closed
