### ISSUE TITLE
"long press" funktioniert nicht

### ISSUE THREAD

**Issue by detlefh68** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#16]
Hallo Daniel,

zunächst möchte ich erst einmal sagen, dann du hier ein echt super Projekt durchgeführt hast! 
Ich bin total begeistert :-)
Leider funktioniert bei mit "long_press" nicht. Ich habe die minimale Konfiguration genutzt.
Alles anderen Funktionen sind prima. Gibt es für die Funktion "long_press" etwas Bestimmtes oder Wichtiges
zu beachten?

Viele Dank und Grüße
Detlef

**Comment by detlefh68** [comment]
Hallo,
nach langen Probieren habe ich es "gemerkt"....der "long_press" ist ja wirklich sehr lang. 
Das Tastfeld muss ja so ca. 10s gedrückt werden bis "long_prees auslöst. Kann man die Zeit evtl. verkürzen?

Viele Grüße
Detlef

**Comment by TeDeVPrime** [comment]
yeah the long_press really takes a long time in order to work. can we reduce the time?

**Comment by danielscheidler** [comment]
This long-press event is sth. on the Touch-Controller, nothing I can modify for the timings in my esp code
