### ISSUE TITLE
Invalid encryption key

### ISSUE THREAD

**Issue by rulandu** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#31]
i get this error. even if I delete the key api, and note, it asks me for the key once flashed

“ERROR Error auth result: Error: Authentication invalid. Is the password correct?”

this is the log:

INFO ESPHome 2024.2.0
INFO Reading configuration /config/esphome/tx-ultimate.yaml…
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See [Frequently Asked Questions — ESPHome](https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins)
WARNING GPIO15 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See [Frequently Asked Questions — ESPHome](https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins)
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See [Frequently Asked Questions — ESPHome](https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins)
INFO Detected timezone ‘Europe/Madrid’
INFO Detected timezone ‘Europe/Madrid’
INFO Starting log output from 192.168.2.167 using esphome API
INFO Successfully connected to tx-ultimate @ 192.168.2.167 in 0.051s
WARNING tx-ultimate @ 192.168.2.167: Connection error occurred: tx-ultimate @ 192.168.2.167: Invalid encryption key: received_name=tx-ultimate
WARNING Can’t connect to ESPHome API for tx-ultimate @ 192.168.2.167: Error while finishing connection: Finishing connection cancelled due to fatal exception: tx-ultimate @ 192.168.2.167: Invalid encryption key: received_name=tx-ultimate: received_name=None (InvalidEncryptionKeyAPIError)

any idea?

Edit. Its solved flashing with espflasher insted of chrome
ty !!

**Comment by danielscheidler** [comment]
I'd say, change of ota password require flashing once over usb.

change of api encryption require to remove and add the device into HA again.
