### ISSUE TITLE
nightlight cannot be turned off

### ISSUE THREAD

**Issue by Delphius7** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#41]
First of all thanks for your great work. I bought 8 switches after I found your integration and I am very happy with them.

However I have one issue with nightlight:
Generally I have nightlight turned off in my yaml code (nightlight: "off") and control the nightlight via home assistant automations.
So the nightlight is tuned on and off at a certain times or events.
However turning off e.g. in the morning fails regularly. In HA the switch shows off but some of the switches still have the nightlight on.
Sometimes 5 of 5 fail and sometimes only 2 of 5. I am not able to find any correlation.
Also switching the nightlight on/off in HA does not fix this, the nightlight stays on.
A reboot of the switch makes them controllable again.

Do you guys have any idea what could be the issue?

Thanks in advance!

**Comment by tomadan1968** [comment]
The same problem for me...

**Comment by Elkropac** [comment]
I have found the problem in code, i think,
Just replace any instance of 
`return id(nightlight).state || id(nightlight_active).state;`
with
`return (id(nightlight).state || id(nightlight_active).state);`

**Comment by tomadan1968** [comment]
> I have found the problem in code, i think, Just replace any instance of `return id(nightlight).state || id(nightlight_active).state;` with `return (id(nightlight).state || id(nightlight_active).state);`
> 
> PR #60

Hello and thank you for the answer, please if you can also post the lines in the yaml where they need to be modified because it appears in several lines....thank you.

**Comment by Elkropac** [comment]
@tomadan1968  it's in the PR #60 . You can just replace any occurance of 
`return id(nightlight).state || id(nightlight_active).state;`
with
`return (id(nightlight).state || id(nightlight_active).state);`

in your yaml file

**Comment by tomadan1968** [comment]
> @tomadan1968 it's in the PR #60 . You can just replace any occurance of `return id(nightlight).state || id(nightlight_active).state;` with `return (id(nightlight).state || id(nightlight_active).state);`
> 
> in your yaml file

Ah...ok, thank you !

**Comment by Elkropac** [comment]
@tomadan1968 does it work for you? I have discovered, that it fixes the problem only on first day, next day, i cannot shutdown the nightlight again ...

**Comment by Delphius7** [comment]
> @tomadan1968 it's in the PR #60 . You can just replace any occurance of `return id(nightlight).state || id(nightlight_active).state;` with `return (id(nightlight).state || id(nightlight_active).state);`
> 
> in your yaml file

My workaround so far was to reboot the switch right after I set the nightlight to OFF. This way it always worked.
Thanks for your solution, I will test it now.

However I am a bit confused... I understand that this is the correct definition but I don't understand why it was mostly working and then suddenly not working any more after some days. Do you have any explanation for this behavior?
Thanks!

**Comment by tomadan1968** [comment]
> > este în PR #60 . Puteți înlocui orice apariție a cu `return id(nightlight).state || id(nightlight_active).state;``return (id(nightlight).state || id(nightlight_active).state);`
> > în fișierul yaml
> 
> Soluția mea de până acum a fost să repornesc comutatorul imediat după ce am setat lumina de noapte la OFF. În acest fel a funcționat întotdeauna. Mulțumesc pentru soluție, o voi testa acum.
> 
> Cu toate acestea, sunt puțin confuz... Înțeleg că aceasta este definiția corectă, dar nu înțeleg de ce a funcționat în mare parte și apoi brusc nu a mai funcționat după câteva zile. Aveți vreo explicație pentru acest comportament? Mulţumesc!

Hello, you have to go here and read how to make it local because it has gps coordinates in the tx_ultimate.yaml file and they belong to the creator and with every update it loads them from there and the light turns on and off depending on its location, no take into account your automation or if you turn it off manually, and after you move them locally, i.e. to your server, you can put your coordinates or you can delete them from there and it will work depending on your automation or manual switching.

![image](https://github.com/user-attachments/assets/bafa8184-ba2d-4acc-9acc-1b157dedb13a)

https://github.com/SmartHome-yourself/sonoff-tx-ultimate-for-esphome

this is my modification to load local yaml:
![image](https://github.com/user-attachments/assets/fbc480bb-190f-4257-8adc-7f8af36c8565)

![image](https://github.com/user-attachments/assets/9604fba0-b5f6-4e62-ad13-a09eeb746126)
![image](https://github.com/user-attachments/assets/1eb1ec1e-179a-4e87-9a5d-787676e70041)

**Comment by Elkropac** [comment]
> > @tomadan1968 does it work for you? I have discovered, that it fixes the problem only on first day, next day, i cannot shutdown the nightlight again ...
> 
> Yes, it still needs to be changed in esp, in the yaml of the switch: ![image](https://private-user-images.githubusercontent.com/99090481/379767553-481a5506-7eea-4b57-b63e-655ed81b6068.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDI3OTQsIm5iZiI6MTcyOTg0MjQ5NCwicGF0aCI6Ii85OTA5MDQ4MS8zNzk3Njc1NTMtNDgxYTU1MDYtN2VlYS00YjU3LWI2M2UtNjU1ZWQ4MWI2MDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA3NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZDdkYmJjNmRiN2Q3NjRmMjJhMTAyOWJjNWY4OGNkYjJiZDgxZmZlYWViZmUyMjY0NzkyNGEwYzFiMGMwYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WOdnyC3L6YzBifpgAXp7DIEujMKEvW2nOCXbCXubP0s)

Ok, great it works for you. I have `nightlight` set to `off` in my common config file.

I have have set this for debuging 
```
  - platform: template
    name: "Nightlight Internal"
    id: nightlight
    internal: false
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - script.execute: refresh_led_default
    on_turn_off:
      then:
        - script.execute: refresh_led_default
```
so i can see state of this in home assistant.
I was thinking, that it restores the `on` state from the time before I updated `nightlight` to `off` in my config.
But it was already `off` all the time ... so i'm confused.

It works now for me now, it turned off this morning (using nodered and the `nighligt_active` switch)

I don't know esphome well, but there was maybe a conflict in names? Both `nightlight` templates have same `name` (but different `id`)  in original config

**Comment by Delphius7** [comment]
I was able to fix the issue myself. Here the solution in case someone needs it:
It turned out that `nightlight: "off"` is not enough. If the nightlight switch in HA (template nightlight_active) is turned on and then the device is rebooted the `nightlight: "off"` does not work and the state is suddenly ON. This means that even after turing OFF  the nightlight switch in HA it stays on.
The solution is: to change `restore_mode: ALWAYS_OFF` in template nightlight.

**Comment by Elkropac** [comment]
@Delphius7 Yes, i also set nightlight template to `restore_mode: ALWAYS_OFF` in PR #60 

Because in current code, when variable `nightligth` is set to `off`, i does not adjust internal `nightlight` template anymore. 

So when you set `nightligth` to `off` and uploaded the code during night, the internal `nightlight` template stays `on` forever

**Comment by Delphius7** [comment]
> @Delphius7 Yes, i also set nightlight template to `restore_mode: ALWAYS_OFF` in PR #60
> 
> Because in current code, when variable `nightligth` is set to `off`, i does not adjust internal `nightlight` template anymore.
> 
> So when you set variable `nightligth` to `off` and uploaded the code during night, the internal `nightlight` template stays `on` forever

oooh I see now... 
If I would have read your PR more carefully I could have saved a lot of time finding this out myself. ;-|
Thanks for your help!

**Comment by kicsikocsi** [comment]
The problem still exists for me. I'm not using Github code locally, were there no corrections in that uploaded file?
