### ISSUE TITLE
failed to merge?

### ISSUE THREAD

**Issue by percy-punch** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#62]
Hi all having an issue flashing:  I am installing via "plug into this Computer" option
 can anyone advise

`Building .pioenvs/familyroom-tx-ultimate/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/familyroom-tx-ultimate/firmware.bin"], [".pioenvs/familyroom-tx-ultimate/firmware.elf"])
usage: esptool merge_bin [-h] --output OUTPUT [--format {raw,uf2,hex}]
                         [--chunk-size CHUNK_SIZE] [--md5-disable]
                         [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                         [--flash_mode {keep,qio,qout,dio,dout}]
                         [--flash_size {keep,256KB,512KB,1MB,2MB,2MB-c1,4MB,4MB-c1,8MB,16MB,32MB,64MB,128MB}]
                         [--spi-connection SPI_CONNECTION]
                         [--target-offset TARGET_OFFSET]
                         [--fill-flash-size {256KB,512KB,1MB,2MB,4MB,8MB,16MB,32MB,64MB,128MB}]
                         <address> <filename> [<address> <filename> ...]
esptool merge_bin: error: argument <address> <filename>: [Errno 2] No such file or directory: '/data/build/familyroom-tx-ultimate/.pioenvs/familyroom-tx-ultimate/bootloader.bin'
*** [.pioenvs/familyroom-tx-ultimate/firmware.bin] Explicit exit, status 2
========================= [FAILED] Took 79.24 seconds =========================`

**Comment by barth11** [comment]
Try going with Manual Download
![{48955BF3-A187-420A-BC99-6734BBEC297A}](https://github.com/user-attachments/assets/8ddae87e-9eaf-4bb9-b6da-f278106ba3ad)
and the using
https://web.esphome.io/?dashboard_install
It's working flawlessly. Tested multiple times.

**Comment by percy-punch** [comment]
It seems it was a browser problem.  Revoked chromes USB terminal access and restarted chrome and it built and installed.  I did flash the wrong setup for some reason but the OTA worked without issue.  Thanks for the reply
