### ISSUE TITLE
Flaschen funktioniert nicht esp bleibt im bootloop

### ISSUE THREAD

**Issue by Chase295** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#8]
Hallo zusammen ich bin mitlerweile komplett ratlos. Immer wenn ich versuche esphome auf meinen Sonoff Ty ultimate Flasche funktoert das ohne Probleme (wie im Video nur über esphomeflsher. Aber dieser baut keine Verbindung mit dem Internet oder sonstiges auf auch kein Hotspot. Im seriellen Monitor habe ich jedoch ein bootloop von dieser "Fehler" Meldung. Hatt irgendwer eine Idee ich bin komplett ratlos. Der Boot "Knopf" ist den ganzen Flash Durchgang gedrückt.

 ![image](https://github.com/SmartHome-yourself/sonoff-tx-ultimate-for-esphome/assets/102094432/52efcef3-2c51-466e-b15b-39f9feeeaeb3)

`rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 153911750, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
[I][logger:262]: Log initialized
[C][ota:469]: There have been 2 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][uart.arduino_esp32:077]: Setting up UART...
[C][switch.gpio:011]: Setting up GPIO Switch 'Kammer Lichtschalter Vibration'...
[C][switch.gpio:011]: Setting up GPIO Switch 'PA Power'...
[C][switch.gpio:011]: Setting up GPIO Switch 'touch panel power'...
[C][switch.gpio:011]: Setting up GPIO Switch 'Kammer Lichtschalter L1'...
[C][switch.gpio:011]: Setting up GPIO Switch 'Kammer Lichtschalter L2'...
[C][switch.gpio:011]: Setting up GPIO Switch 'Kammer Lichtschalter L3'...
[C][i2s_audio:024]: Setting up I2S Audio...
[I][log:012]: Tx Ultimate Touch is initialized
[C][wifi:038]: Setting up WiFi...
[C][wifi:048]: Starting WiFi...
[C][wifi:049]:   Local MAC: 54:43:B2:71:98:8C
ets Jul 29 2019 12:21:46 `

**Comment by Jaxon77** [comment]
Hast Du den Schalter im zusammengebauten Zustand mit externer 230v Versogung getestet? Anscheinend reicht die 3,3V Versorgung über die Programmierpins nicht zum Booten.

**Comment by Chase295** [comment]
Ja habe ich jetzt habe ich noch einiges ausprobiert und nun geht es. Trotzdem vielen dank. Nun habe ich nur noch ein problem mit dem als online anzeigen aber er ist ereichbar daher ist es ein anderes ticket bei esphome direkt. Nun kann ich ihn wenigstens schon mal benutzen:)
